spring:
  shardingsphere:
    rules:
      #加密
      encrypt:
        encryptors:
          mobile-encryptor:
            type: AES
            props:
              aes-key-value: 123456abc
        tables:
          t_order:
            columns:
              phone:
#                cipher-column: phone # 加密列名称
                plain-column: phone # 原文列名称
                cipher-column: phone_cipher # 加密列名称
                encryptor-name: mobile-encryptor # 加密算法名称（名称不能有下划线）
        queryWithCipherColumn: true # 是否使用加密列进行查询。在有原文列的情况下，可以使用原文列进行查询